import hashlib
from os import walk
import os

#set the path to the directory you want to inspect
path = "D:\Downloads"
os.chdir(path)

files_to_check = []
#one of the hashs generated by our V1 Version, we will use this as a proxy for real malware hashes
hashs_to_check = ["3dd1a00cba0362ecb8c669379efefdc5435007b09401714925da0ca9ea62d5ad"]
sha256_hash = hashlib.sha256()

files = []

def print_hash(str):
    with open(file,"rb") as f:
        # Read and update hash string value in blocks of 4K
        for byte_block in iter(lambda: f.read(4096),b""):
            sha256_hash.update(byte_block)
        print(sha256_hash.hexdigest())
        if sha256_hash.hexdigest() in hashs_to_check:
            #if a generated hash is in hashs_to_check (= if our Test File is inside the directory we´re inspecting)
            print("Warning!")
        else:
            pass

#get all filenames from the specified directory
for (dirpath, dirnames, filenames) in walk(path):
    files_to_check.extend(filenames)
    break

   
for file in files_to_check:
    print_hash(file)
